// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _014_teste.Data;

#nullable disable

namespace _014_teste.Migrations
{
    [DbContext(typeof(ProdutoDbContext))]
    partial class ProdutoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("_014_teste.Data.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<double>("Preco")
                        .HasColumnType("REAL");

                    b.Property<int>("Quant")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Descr = "Excelente notebook",
                            Nome = "Laptop",
                            Preco = 2000.02,
                            Quant = 10
                        },
                        new
                        {
                            Id = 1002,
                            Descr = "Um MS Office",
                            Nome = "Microsoft Office",
                            Preco = 400.99000000000001,
                            Quant = 50
                        },
                        new
                        {
                            Id = 1003,
                            Descr = "Um mouse que funciona",
                            Nome = "Mouse",
                            Preco = 12.02,
                            Quant = 20
                        },
                        new
                        {
                            Id = 1004,
                            Descr = "Armazene incríveis 256GB de dados",
                            Nome = "HD USB",
                            Preco = 5.0,
                            Quant = 200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
